before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y z80asm z80dasm
  - wget http://www.esw-heim.tu-clausthal.de/~marco/smorbrod/acme/current/acme091src.tar.gz
  - tar xzf acme091src.tar.gz
  - make -C acme091/src install

language: python

script: python ./tools/tests.py
