sudo: false

language: python

addons:
  apt:
    packages:
      - cpmtools
      - z80asm
      - z80dasm

before_install:
  # srec_cat
  - sudo apt-get install -qq -y srecord

  # as6500, aslink
  - wget -q -U travis http://6502.org/tools/asm/asxs5p20.zip
  - unzip -q asxs5p20.zip
  - make -C asxv5pxx/asxmak/linux/build as6500 aslink
  - export PATH=$PATH:$PWD/asxv5pxx/asxmak/linux/build

  # acme
  - wget https://www.mirrorservice.org/sites/ftp.cs.vu.nl/pub/minix/distfiles/backup/acme091src.tar.gz
  - tar xzf acme091src.tar.gz
  - make -C acme091/src install BINDIR=$PWD/acme-bin
  - export PATH=$PATH:$PWD/acme-bin

script:
  - python ./tools/tests.py
  - make -C terminals/cbm2
  - make -C terminals/pet_original
  - make -C terminals/pet_speedcode
