# Print mapping of PET sectors to CP/M sectors

import sys

formats = {"d64":"4040", "d80":"8050", "d82":"8250"}
if len(sys.argv) != 2 or sys.argv[1] not in formats:
    msg = "Usage: python pet_to_cpm_sectors.py %s\n" % (
        "|".join(sorted(formats)))
    sys.stderr.write(msg)
    sys.exit(1)
drive = formats[sys.argv[1]]

# Read PET data lines generated by sectors.asm
with open("%s.csv" % drive) as f:
    pet_lines = f.readlines()

with open("8050.csv") as f:
    lines = f.readlines()

# pet sector: [cp/m sector, cp/m sector]
pet_to_cpm = {}
for line in lines:
    parts = [ int(x, 16) for x in line.split(",") ]
    cpm_track, cpm_sector, pet_track, pet_sector = parts

    k = "%02d_%02d" % (pet_track, pet_sector)
    v = "%02d_%02d" % (cpm_track, cpm_sector)
    if not k in pet_to_cpm:
        pet_to_cpm[k] = []
    pet_to_cpm[k].append(v)

# print results
last_track = "01"
for k in sorted(pet_to_cpm.keys()):
    # print a blank line between tracks
    track = k.split("_")[0]
    if track != last_track:
        print("")
    last_track = track

    # print pet sector: [cp/m sector, cp/m sector]
    print("%s: [%s]" % (k, ', '.join(pet_to_cpm[k])))
