#!/usr/bin/env python
'''
Convert a CP/M image into a SoftBox-formatted D64 image

Usage: python cpm_to_d64.py <input.cpm> <output.d64>
'''

import sys
import base64

# This is the data for tracks 16, 17, and 18 that allows the disk to
# boot the SoftBox system.  These tracks hold normal CBM filesystem
# data.  They contain the CBM directory, terminal program that runs
# on the PET/CBM, and the CP/M system image file.
boot_tracks = base64.b64decode('''
    EArS+t/lKsHpe5VfepxX4SvD5N/lKsHpGdoP4HmVeJzaD+Dr4SPD+t/hxdXl
    6yrO6RlETc0e6tEqtelzI3LRKrfpcyNywXmTT3iaRyrQ6evNMOpNRMMh6iHD
    6U464+m3Hw3CReBHPgiWTzri6Q3KXOC3F8NT4IDJKkPfERAAGQk63em3ynHg
    biYAyQleI1bryc0+4E8GAM1e4CLl6ckq5el9tMk6w+kq5ekpPcKQ4CLn6TrE
    6U864+mhtW8i5enJKkPfEQwAGckqQ98RDwAZ6yERABnJza7gfjLj6et+MuHp
    zabgOsXppjLi6cnNruA61en+AsLe4K9POuPpgXfrOhALR83cCs3cCirBNysr
    5bgOAMp8JAzN3Ar+DcqDJLjCbyTNnQq4ym8kzekKzXsL/gAAmST+O8qZJLjK
    mST+DeEiwTfC2CR5/gLa2CTN1gpHzdwKzdwKw7skxc3TFcHN3Ar+Dci4wrMk
    zdYKuMrSJM2dCv4sykkkyc3TFcNJJM0DD/U6JDm3+hMX8c3TFXn+LMpJJMnN
    SR71eOaDxKoE8cnNWhnNewv+IsoKJf4nxHQET83cCv4NyEfN1gq5yiAleM3T
    FcMLJc3zCs3WCrnKOSV49oDN0xXNnQr+LMr6JMl4zdMVec3zCsMRJc1aGc1Y
    Jc0kJCpNOBk6TDhHw3Ejze4QDOHNUejNnOPDAePNUejDvOXNUejD/uXNcuHN
    UejDJOXNUejNFuTDAeMqr+nDKek6Qt/DAd/rIrHpw9rhKr/pwynpKq3pwynp
    zVHozTvkwwHjKrvpIkXfyTrW6f7/wjvpOkHfwwHf5h8yQd/JzVHow5PnzVHo
    w5znzVHow9LnKkPffS9ffC8qr+mkV32jXyqt6esir+l9o298omcirenJOt7p
    t8qR6SpD3zYAOuDpt8qR6Xc63+ky1unNRegqD9/5KkXffUTJzVHoPgIy1ekO
    AM0H58wD5snlAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAEA3kJTqmN7fCWCXBryE0DSLBN8PkJfY39c17C/48xHQEzdYKt8KPJs2d
    Cs3WCv4mwo8mzZ0Kw3cmKsE3KxEAACN+/j7CnyZUXf4NwpYmI+UqwTd6s8x0
    BDp2OP4gwsMmzTYN4SLBN8pUJsNPJuHDYSbNCAtPxcR0BDfNqAwjfvZAd8Hm
    IMywBH7mgMSMBB8fH7Z3ef4syscmyRGWOAEAT8MAJw4AEeY4BjvNewsqwTcr
    fiP+HCHlL4VvPv+MZ3u5whchepDCFyHhPMkzM8P4IK/JAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAO4eZ/d/H+f8IA
    5zrV6f4BwgDnzdLgzVrlIUXffrfC/uY9MuPpNgDD0uCvMtXpxSpD3+shIQAZ
    fuZ/9X4XI34X5h9Pfh8fHx/mD0fxI24sLS4GwovnISAAGXchDAAZeZbCR+ch
    DgAZeJbmf8p/58XVzaLk0cEuAzpF3zzKhOchDAAZcSEOABlwzVHkOkXfPMJ/
    58HFLgQMyoTnzSTlLgU6Rd88yoTnwa/DAd/lzWnhNsDhwX0yRd/DeOEO/80D
    58zB5ckOAM0D58wD5snrGU4GACEMABl+D+aAgU8+AIhHfg/mD4BHIQ4AGX6H
    h4eH9YBH9eF94bXmAckODM0Y4yoQD0JBESIkBJAICSAJCEIBEQJIQgQEhCSE
    BCQgIQgQkCQkQhCEJIEhCSBCCCEJJCQiCQiEIhIJIA0KNjBLIFBFVCBDUC9N
    IHZlcnMuIDIuMg0KKGMpIDE5ODEgS2VpdGggRnJld2luDQpSZXZpc2lvbiA0
    LzcvODEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAEBDkfhK+wh/lw/3kzZTk682U5OsavsIf5RMjGr7CH+UNEyMNws3k
    Aez/CesJGr7aF+V3AQMACesJfhI+/zLS6cMQ5CFF3zXJzVThKkPf5SGs6SJD
    3w4BzRjjzfXh4SJD38jrIQ8AGQ4Rr3cjDcJG5SENABl3zYzhzf3jw3jhrzLS
    6c2i5M314cgqQ98BDAAJfjzmH3fKg+VHOsXpoCHS6abKjuXDrOUBAgAJNH7m
    D8q25Q4PzRjjzfXhwqzlOtPpPMq25c0k5c314cq25cOv5c1a5M274K/DAd/N
    Bd/DeOE+ATLV6T7/MtPpzbvgOuPpIeHpvtrm5f6AwvvlzVrlrwAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEtLiOkHfvsL24iN+1iTC9uI9MkXf
    DgHNa+LNjOHD0uI61OnDAd/F9TrF6S9HeaBP8aCR5h/ByT7/MtTpIdjpcSpD
    3yLZ6c3+4c2h3w4AzQXizfXhypTjKtnp6xr+5cpK49XNf+HR0pTjzV7hOtjp
    TwYAebfKg+Ma/j/KfON4/g3KfOP+DBrKc+OW5n/CLePDfOPFTs0H48HCLeMT
    IwQNw1PjOurp5gMyRd8h1Ol+F9Cvd8nN/uE+/8MB381U4Q4MzRjjzfXhyM1E
    4c1e4TblDgDNa+LNxuHNLePDpONQWXmwytHjC9XFzTXiH9Ls48HRKsbpe5V6
    nNL04xPF1UJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAU4el3
    yQwNyHy3H2d9H2/D6+AOgCq56a+GIw3C/eDJDA3IKcMF4cU6Qt9PIQEAzQTh
    wXm1b3i0Z8kqrek6Qt9PzergfeYBySGt6U4jRs0L4SKt6SrI6SPrKrPpcyNy
    yc1e4REJABl+F9AhD9zDSt/NHuHIIQ3cw0rfKrnpOunphW/QJMkqQ98RDgAZ
    fsnNaeE2AMnNaeH2gHfJKurp6yqz6XuWI3qeyc1/4dgTcitzyXuVb3qcZ8kO
    /yrs6esqzOnNleHQxc334Cq96esq7OkZwQzKxOG+yM1/4dDNLOHJd8nNnOHN
    4OEOAc2438Pa4c3g4c2y3yGx6cPj4SG56U4QAyQ6aje3wDp2OP5VwDwydjjJ
    zVoZzSQkzUkezTUWef4symslyTpxNz36piVHMnE3OnI3PbjClCUycjc6cjeQ
    nzwypjfN0yUyczfD8wrNegTJOnM3t8R6BDpxN7fMegQhcjeWys8lPcLzCjQ9
    MqY3PDJzN8PzCjXDxSU6cTdf/jI+ANBXIXQ3GTd+yfXN0yURczfS8CUad68S
    IXE3NDqmN7fKExfxMqY3IXI3t8g0yc1aJnqzw+QlzVomerMvyuQlr8PkJTpq
    N83zCj3D5CU6ajfN8wq3w+Ql9jf1OqY3t8phJs0IC83XC8JJJuagwlQmzcEL
    ylQm8Z/D5CXxP5/DEAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAMMA8MMD8MMG8MMJ8MMM8MMP8MMS8MMV8MMY8MMb8MMe
    8MMh8MMk8MMn8MMq8MMt8MMw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAEBgV67gQCGwAgIAAAAAAAAv///////wgB
    AgAAAAAAsQSyBbMG6g7rD9Ec1x3FEdIS1BP0E9kU+RSrGqoauhq7GtoavRuo
    AKkAAAXyzSDDMMol5f/rc3LRE/olUAE5IVoZzXsLzekK/iLKXCT+J8LYJBAF
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgkABCAAAA
    AAAAQQiEkIEIkkkJJAJAhAEIEiQAAggBAEIIEAQkEICJCEAkJIIEkAISEhJA
    ISQIRCAQiQkIiQIRCEkJJJJJCSQkJJCSJBABCQgQAkPfESEAGeVyI3Ijcs31
    4coM6M1e4REPAM2l5+HlX3mWI3ieI3ue2gbocytwK3HNLePD5OfhySpD3xEg
    AM2l5yEhABlxI3Ajd8kqr+k6Qt9Pzerg5evNWd/hzEfffR/YKq/pTUTNC+Ei
    r+nDo+I61ukhQt++yHfDIeg+/zLe6SpD337mHz0y1un+HtJ16DpC3zLf6X4y
    4Onm4HfNReg6Qd8qQ9+2d8k+IsMB3yEAACKt6SKv6a8yQt8hgAAisenN2uHD
    IejNcuHNUejDUeTNUejDouQOAOt+/j/KwujNpuB+/j/EcuHNUegOD80Y48Pp
    4SrZ6SJD381R6M0t48PpADkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    ABAEMuPpOkXft8L75c134M2E4Mr75c2K4M3R382y38PS4MMF3z4BMtXpPgAy
    0+nNVOEqQ9/NR+HNu+A64+n+gNIF38134M2E4A4Awm7mzT7gMtfpAQAAt8o7
    5k8LzV7gRE3NvuN9tMJI5j4CwwHfIuXp6ypD3wEQAAk63em3OtfpymTmzWTh
    c8Ns5k8GAAkJcyNyDgI6Rd+3wMXNiuA61ek9PcK75sHFeT09wrvm5Sq56Vd3
    IxTyjObN4OEq5+kOAiLl6cXN0d/BzbjfKuXpDgA6xOlHpbgjwprm4SLl6c3a
    4c3R38HFzbjfwTrj6SHh6b7a0uZ3NA4CAAAhAAD1zWkAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAEAbNNeIf0uzj0cHDwOMXPM1k4uHRyXmwwsDj
    IQAAyQ4AHiDVBgAqQ98J681e4cHNT9/Nw9/DxuHNVOEODM0Y4ypD334REAAZ
    d8314cjNROEOEB4MzQHkzS3jwyfkDgzNGOPN9eHIDgAeDM0B5M0t48NA5A4P
    zRjjzfXhyM2m4H715c1e4esqQ98OINXNT9/NeOHRIQwAGU4hDwAZRuHxd3m+
    eMqL5D4A2ovkPoAqQ98RDwAZd8l+I7YrwBp3EyMadxsrya8yRd8y6uky6+nN
    HuHAzWnh5oDADg/NGOPN9eHIARAAzV7hCesqQ98JDhA63em3yujkfrcawtvk
    d7fC4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQCCNGwyTqKrnp
    6yqx6Q6Aw0/fIerpfiO+wDzJIf//IurpySrI6esq6ukjIurpzZXh0hniw/7h
    Ourp5gMGBYcFwiDiMunpt8DFzcPfzdThwcOe4XnmBzxfV3kPDw/mH094h4eH
    h4exT3gPDw/mH0cqv+kJfgcdwlbiydXNNeLm/sGxDxXCZOJ3yc1e4REQABnF
    DhHRDcjVOt3pt8qI4sXlTgYAw47iDcVOI0blebDKneIqxul9kXyY1Fzi4SPB
    w3XiKsbpDgPN6uAjRE0qv+k2ACMLeLHCseIqyunrKr/pcyNyzaHfKrPpNgMj
    NgDN/uEO/80F4s314cjNXuE+5b7KEQoABAANBDIAnigxMDM5KQAAAExmBCAg
    U09GVEJPWCBMT0FERVIgKEMpIENPUFlSSUdIVCAxOTgxIEtFSVRIIEZSRVdJ
    TiAgIC0tLS0gIFJFVklTT04gOiAgNSBKVUxZIDE5ODEgICAgIHipT4WQqQaF
    kakAhQipAIUUhRWFFoUXhRiFGYUaqQqNPQtYqQ6NTOgghAepFIUBqQCFBoUL
    qSiFCalVjQCACo0AhM0AhNAISs0AgNACBgmpGiDoBiDUCK0i6K1A6Cn7jUDo
    qTSNI+ipxo0i6KAAiND9qf+NIuipPI0R6I0h6I0j6Kk8jSHorUDoCQaNQOit
    I+gKkPqtIhEMEc3bw/nUDhXD9NQOFsPD1A4XwwUAHv8OIMMFAM0T1YeHh4ch
    79u2MgQAyTrv2zIEAMn+Ydj+e9DmX8k6q9u3ypbVOu/btz4AxL3UEazbzcvU
    ypbVOrvbPTLM2xGs28351MKW1REH1CGAAAaAzULYIbrbNgAjNRGs283a1MqW
    1Trv27fEvdQhCNTNrNTNwtXKp9XN3dXDgtfN3dXNGtUOChEG1M0FAM0p1SEH
    1EYjeLfKutV+zTDVdwXDq9V3IQjUIojUyQ4LzQUAt8gOAc0FALfJDhnDBQAR
    gAAOGsMFACGr2363yDYAr8291BGs283v1Drv28O91BEo1yEA3AYRDSKI1OEB
    CwAjfv4/wgnXBA3CAdd4t8lESVIgRVJBIFRZUEVTQVZFUkVOIFVTRVJbFgEA
    By4hENcOAHn+BtARztsGBBq+wk/XEyMFwjzXGv4gwlTXeckjBcJP1wzDM9ev
    MgfUMavbxXkfHx8f5g9fzRXVzbjUMqvbwXnmDzLv28291DoH1LfCmNcxq9vN
    mNTN0NXGQc2M1D4+zYzUzTnVEYAAzdjVzdDVMu/bzV7WxAnWOvDbt8Kl2s0u
    1yHB118WABkZfiNmb+l32B/ZXdmt2RDajtql2iHzdiIA1CEA1OkB39fDp9RS
    RUFEIEVSUk9SAAHw18On1E5PIEZJTEUAEQ/ZPiDNktQEeP4M0g7Z/gnC2djN
    otTD2djxzcLVwhvZzeTUw5jY0cOG281e1v4LwkLZAVLZzafUzTnVIQfUNcKC
    1yN+/lnCgtcjIojUzVTYEc3bze/UPMzq18OG20FMTCAoWS9OKT8AzV7WwgnW
    zVTYzdDUyqfZzZjUIfHbNv8h8dt+/oDah9nlzf7U4cKg2a93NCGAAM1Z1n7+
    GsqG282M1M3C1cKG28N02T3KhtvN2dfNZtjDCdbN+Nf1zV7WwgnWzVTYEc3b
    1c3v1NHNCdXK+9mvMu3b8W8mACkRAAF8tcrx2SvlIYAAGeXN2NURzdvNBNXR
    4cL72cPU2RHN2xEOtLcwN17/ORtTRkhdS7s1QURHSg1MQDYJV1JZXElQf1FF
    VFUKT1s0AUNCri7/ATNaVk6sMP//MgBYIE0e/68xX7O2uf+6//+qqqqqqqqq
    qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
    qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
    qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
    qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoREQAZ
    EQDUfZN8mtJx28Ph2uE9wnHbzWbYzV7WIfDb5X4yzds+EM1g1uF+Mt3brzLt
    2xFcACHN2wYhzULYIQjUfrfKPtv+IMo+2yPDMNsGABGBAH4St8pP2wQjE8ND
    23gygADNmNTN1dXNGtXNAAExq9vNKdXNvdTDgtfNZtjDCdYBetvNp9TDhttC
    QUQgTE9BRABDT03NZtjNXtY6ztvWICHw27bCCdbDgtcAAAAAAAAAAAAAAAAA
    AAAAAAAkJCQgICAgIFNVQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERDEBPAJiLECyJECiNDzqSCR
    AmAgiAmkBMjECfAIsQKIkQLI0POIqSCRAmCpAIUEIIgJpQIYZQmFDaUDaQCF
    DqkYOOUFqkyeCKnAoIOmCeBQ0ASpgKCHhQ2EDqkAhQSlDcUC0AalDsUD8B+l
    DYUPOOUJhQ2lDoUQ6QCFDqAAsQ2RD8jECdD3TFEJoACpIJECyMQJ0PlgSKkA
    hQOlBYUCCgplAgoKJgMKJgOFAqUJyVDQBAYCJgMYpASlA2mAhQNoYKkChQtg
    xgvwDDjpIMUJsAKFBEyNBzjpIMkZsPaFBUyNB603C404C6IAjjoLjjsLjhDo
    qf+NNwupCo05C6AIrRETMsbcAbrczdPdwc3T3SEO3342ALfAwwnqzfvczRTd
    2PVPzZDd8cn+Dcj+Csj+Ccj+CMj+IMk6Dt+3wkXdzQbq5gHIzQnq/hPCQt3N
    Cer+A8oAAK/JMg7fPgHJOgrft8Ji3cXNI93Bxc0M6sHFOg3ft8QP6sF5IQzf
    /n/INP4g0DV+t8h5/gjCed01yf4KwDYAyXnNFN3SkN31Dl7NSN3x9kBPef4J
    wkjdDiDNSN06DN/mB8KW3cnNrN0OIM0M6g4IwwzqDiPNSN3Nyd06DN8hC9++
    0A4gzUjdw7ndDg3NSN0OCsNI3Qr+JMgDxU/NkN3Bw9PdOgzfMgvfKkPfTiMR
    EmglE6YL0BbJILAVCqq9HgeFDb0fB4UOIBsHTI0HTLgJTJkHbA0AiQd/B4QH
    iQfJCMwI1AheB90H3wgLCO0H/wdFCFQIWQhKCDsJHgleCGsI0QfXB3EHYwdP
    CB8IswnuCAYJGAiJB6kHTNL/rUzoSKkOINL/aI1M6GCtTOhIqY4g0v9ojUzo
    YKn/hRNgqX+FE2BgIPQHIIgJsQKFB6UMhQZgyUCQ7clgsAUpP0ysB8mAsCAp
    X6opP/AVyRuwEYpJQKqtTOhKSrAGiikfTIoHikyKByl/CUBMigepDI1M6GCp
    Do1M6GCmBNAIpgmlBfAFxgXKhgRgpAXw+8YFYKYKEADDAd86AwDDAd8hAwBx
    yetNRMPT3c0j3TJF38k+AcMB3wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhC9xeI1br6QwN
    yBp3EyPDUN86Qt9PzRvqfLXIXiNWIyKz6SMjIrXpIyMit+kjI+si0OkhuekO
    CM1P3yq76eshwekOD81P3yrG6Xwh3ek2/7fKnd82AD7/t8nNGOqvKrXpdyN3
    KrfpdyN3yc0n6sO7380q6rfIIQncw0rfKurpDgLN6uAi5eki7Okh5elOI0Yq
    t+leI1Yqtel+I2ZveZN4mhEU6Kk0jSHoriDoimqpf7AGpAjQAqm/jSLorSDo
    KT/JP9D3qf+NIuiKapDBapAMapAMapAXapBdTFsFTMYFIM8FojyOIegg6AZM
    5wQgzwWFDSDPBYUOojyOIeggGwdM5wQgzwWFESDPBYUSIM8FhQ0gzwWFDqAA
    IM8FkQ3I0ALmDqUROOkBhRGlEukAhRIFEdDlTOcEIM8FhREgzwWFEiDPBYUN
    IM8FhQ6gAIjQ/bENIPsFyNAC5g6lETjpAYURpRLpAIUSBRHQ5UznBCAuBiD7
    BUznBK1A6AkCjUDoLEDoMPutIOhJ/0itQOgp/Y1A6Kk8jSHoLEDoEPupNI0h
    6GgRAcNc18NY138AAA0KU0VUIFVQUEVSDQpESVINClNFVCBMT1dFUg0KU1RB
    VCAqLioNClNVQk1JVCBHTkFTSEVSDQoaGhoaGhoaGhoaGhoaGhoaGhoaGhoa
    GhoAAAAAAAAAAChjKSBDb3B5cmlnaHQgMTk4MSBEaWdpdGFsIFJlc2VhcmNo
    AAAAAAAI1AAAXw4CwwUAxc2M1MHJPg3NktQ+CsOS1D4gw5LUxc2Y1OF+t8gj
    5c2M1OHDrNQODcMFAF8ODsMFAM0FADLu2zzJDg/Dw9SvMu3bEc3bw8vUDhDD
    w9QOEcPD1A4Sw8PUEc3bw9/UDhPDBQDNBQC3yQ4Uw/TUEQIGGr7Cz9cTIwXC
    /dXJzZjUKorUfv4gyiLWt8oi1uXNjNThI8MP1j4/zYzUzZjUzd3Vw4LXGrfI
    /iDaCdbI/j3I/l/I/i7I/jrI/jvI/jzI/j7IyRq3yP4gwBPDT9aFb9AkyT4A
    Ic3bzVnW5eWvMvDbKojU681P1usiitTr4Rq3yonW3kBHExr+OsqQ1hs679t3
    w5bWeDLw23ATBgjNMNbKudYj/irCqdY2P8Or1ncTBcKY1s0w1srA1hPDr9Yj
    NiAFwrnWBgP+LsLp1hPNMNbK6dYj/irC2dY2P8Pb1ncTBcLI1s0w1srw1hPD
    39YjNiAFwunWBgMjNgAFwvLW6xEDzV7WOvDbt8IJ1iHO2wELAH7+IMoz2CPW
    MP4K0gnWV3jm4MIJ1ngHBweA2gnWgNoJ1oLaCdZHDcII2Ml+/iDCCdYjDcIz
    2HjJBgN+EiMTBcJC2MkhgACBzVnWfsmvMs3bOvDbt8g9Ie/bvsjDvdQ68Nu3
    yD0h79u+yDrv28O91M1e1s1U2CHO237+IMKP2AYLNj8jBcKI2B4A1c3p1Mzq
    18ob2Tru2w8PD+ZgTz4KzUvYF9oP2dF7HNXmA/XCzNjNmNTFzdDVwcZBzZLU
    PjrNktTD1NjNotQ+Os2S1M2i1AYBeM1L2OZ//iDC+djx9f4DwvfYPgnNS9jm
    f/4gyg4AEaqqqqqqqqqqqqqqqqqqqqoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQXN2tQ8wgHa
    AQfazafUzdXVw4bbTk8gU1BBQ0UAzV7WwgnWOvDb9c1U2M3p1MJ52iHN2xHd
    2wYQzULYKojU681P1v49yj/a/l/Cc9rrIyKI1M1e1sJz2vFHIfDbfrfKWdq4
    cMJz2nCvMs3bzenUym3aEc3bzQ7Vw4bbzerXw4bbzWbYwwnWAYLazafUw4bb
    RklMRSBFWElTVFMAzfjX/hDSCdZfOs7b/iDKCdbNFdXDidvN9dU6ztv+IMLE
    2jrw27fKids9Mu/bzSnVzb3Uw4nbEdbbGv4gwgnW1c1U2NEhg9vNQNjN0NTK
    a9shAAHl683Y1RHN28351MIB2+ERgBEEEujNEujQ+EpIsCKlCclQ0Aa95wpM
    DAq9lwrJAfAHkAqNNwuwCO46C9AD7jsLaOiI0NXuEOjOOQvQw603C8n/8CLN
    OAvwHckAEAopf6w6C/ADSRBgyUCQJclgsCGsOwvwAykfYMlA8BXJW7ARrDoL
    0AxIrUzoSkpokAMJIGCsOgvwIKILyQrwGKIIyQzwEqIayR7wDEitTOhKSmiw
    BQmAYIpgyQBgISMlJihfHgwiJCdcKf8Kf1FFVFVPXjc5V1JZSVD/OC9BREdK
    TP80NlNGSEs6/zUqWkNCTTsNMTNYVk4sP/8yKwFAXf8+ATAtAFsgPBv/Lj2y
    tbitOAz//7ERBwAAAAAAAAAAAAAAAAAAAABbFgEABy7DEdyk3KXcq9yx3Osi
    Q9/rezLW6SEAACJF3zkiD98xQd+vMuDpMt7pIXTp5Xn+KdBLIUfcXxYAGRle
    I1YqQ9/r6QPqyN6Q3c7eEuoP6tTe7d7z3vje4d3+3n7og+hF6Jzopeir6Mjo
    1+jg6Obo7Oj16P7oBOkK6RHpLOEX6R3pJukt6UHpR+lN6Q7oU+kE3wTfm+kh
    ytzN5dz+A8oAAMkh1dzDtNwh4dzDtNwh3NzN5dzDAABCZG9zIEVyciBPbiAg
    OiAkQmFkIFNlY3RvciRTZWxlY3QkRmlsZSBSL08k5c3J3TpC38ZBEQbwAkmA
    IIgJkQLmBKYE5AnQEKkAhQSkBcAY0ANMjgjmBWBgqQCFBYUEYKIAhgSGBYYK
    qSCdAICdAIGdAIKdAIOdAISdAIWdAIadAIfo0OVgqQCFBGCpAIUMYKn/hQxg
    qQGFCmCpAIUKYCCICakgkQLIxAnQ+WAgXgimBejgGfAYGKUCZQmFApAC5gOp
    IKAAkQLIxAnQ+fDjYKkAhQKlCYUNqYCFA4UOohigALENkQLIxAnQ96UNhQIY
    ZQmFDaUOhQNpAIUOytDhoACpIJECyMQJ0PlgqQEsqQCmBJ0/C2CiT6kAnT8L
    yhD6YKYE6OBQsAe9Pwvw9oYEYCCICaQJiBEJ5QYAxeXN+9zmf+HB/g3Kwd7+
    CsrB3v4IwhbeeLfK790FOgzfMgrfw3De/n/CJt7DB97v3X4FK8Op3v4Fwjfe
    xeXNyd2vMgvfw/Hd/hDCSN7lIQ3fPgGWd+HD793+GMJf3uE6C98hDN++0uHd
    Nc2k3cNO3v4Vwmvew03e4cPh3f4Swqbexc2x3cHh5cV4t8qK3iNOBcXlzX/d
    4cHDeN7lOgrft8rx3SEM35YyCt/NpN0hCt81wpnew/HdI3cExeVPzX/d4cF+
    /gN4wr3e/gHKAAC52u/d4XAODcNI3c0G3cMB380V6sMB33k8yuDePMoG6sMM
    6s0G6rfKkenNCeoRCGBJ/40i6K1A6AkCjUDoqTyNIegsQOhQ+6k0jSPorUDo
    SpD6qTyNI+ip/40i6K1A6Eqw+mCp/3imCPAUrW8CSKIAxgi9cAKdbwLo5AjQ
    9WhYyf/w4GDmGtAG5hnQAuYY5hSlFM0DBNAoqQCFFOYVpRXJPNAcqQCFFeYW
    pRbJPNAQqQCFFuYXpRfJGNAEqQCFF6UG0BHGAdANqRSFASCICbECSYCRAq03
    C80+C/AKjT4LqRCNPAvQIcn/8B2tPAvwBc48C9ATzj0L0A6pBI09C6kAjTcL
    qQKFASDUCfALpgjgUPAFnW8C5ghoqGiqaEBIpQaFDKn/hQYgiAmlB5ECEgFB
    ABX//x8V//8fFf//HxX//x8V//8fFf//HxX//x8V//8fFf//HxX//x8V//8f
    Ff//HxX//x8V//8fFf//HwSAAgoAAAAAEfz/BxP//wcT//8HE///BxP//wcT
    //8HE///BxL//wMS//8DEv//AxL//wMS//8DEv//AxH//wER//8BEf//ARH/
    /wER//8BQ1AvTSBWMi4yIERJU0ugoKCgWFigMkGgoKCgAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/ghEAS6CgoKCgoKCgoKCg
    oKCgoAAAAAAAAAAAAAkAAACCEQtDUC9NoKCgoKCgoKCgoKCgAAAAAAAAAAAA
    HQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AA==''')


def cpm_to_d64(input_filename, output_filename):
    inp = open(input_filename, "rb")
    out = open(output_filename, "wb")

    pet_track, pet_sector = 1, 0
    cpm_track, cpm_sector = 0, 0

    for i in range(0, 1244):
        # each 256-byte pet sector holds two 128-byte cp/m sectors
        cpm_sector_data = inp.read(128)
        if len(cpm_sector_data) != 128:
            cpm_sector_data = chr(0) * 128
        out.write(cpm_sector_data)

        # increment cp/m track/sector counters
        cpm_sector += 1
        if cpm_sector > 31:
            cpm_track += 1
            cpm_sector = 0

        if i & 1:
            # increment pet track/sector counters
            pet_sector += 1
            if not is_valid_4040_ts(pet_track, pet_sector):
                pet_sector = 0
                pet_track += 1

            # skip over the 3 reserved 4040 tracks: 16, 17, 18
            # 21 sectors on tracks 16 & 17, 19 sectors on track 18
            if pet_track == 16:
                pet_track = 19
                out.write(boot_tracks)
                # TODO: option to write non-bootable disk
                # out.write(chr(0) * 256 * 21) # track 16
                # out.write(chr(0) * 256 * 21) # track 17
                # out.write(chr(0) * 256 * 19) # track 18

    inp.close()
    out.close()


def is_valid_4040_ts(track, sector):
    valid = False
    if track >= 1 and track <= 17:
        valid = sector >= 0 and sector <= 20
    elif track >= 18 and track <= 24:
        valid = sector >= 0 and sector <= 18
    elif track >= 25 and track <= 30:
        valid = sector >= 0 and sector <= 17
    elif track >= 31 and track <= 35:
        valid = sector >= 0 and sector <= 16
    return valid


if __name__ == '__main__':
    if len(sys.argv) < 3:
        sys.stderr.write(__doc__ + "\n")
        sys.exit(1)

    cpm_to_d64(sys.argv[1], sys.argv[2])
