# Read PET data lines generated by make_test_image.py
with open("8050_pet_to_cpm.txt") as f:
    lines = f.readlines()

# find used tracks
used_tracks = set()
for line in lines:
    track, rest = line.split("_", 1)
    used_tracks.add(int(track))

# print unused tracks
all_tracks = set(range(1, max(used_tracks)+1))
for unused_track in (all_tracks - used_tracks):
    print(unused_track)
