# Read PET data lines generated by make_test_image.py
with open("8050_pet_sectors.csv") as f:
    pet_lines = f.readlines()

# Build dict of {identifier: pet track}
ids_to_pet_tracks = {}
for line in pet_lines:
    parts = [ int(x, 16) for x in line.split(",") ]
    pet_track, pet_sector, pet_half, identifier = parts
    ids_to_pet_tracks[identifier] = pet_track

# Read CP/M data lines generated by readall.com
cpm_lines = []
with open("8050_cpm_sectors.csv") as f:
    lines = f.readlines()
for line in lines:
    if "BDOS" in line:
        break
    if "," in line:
        cpm_lines.append(line)

# find which pet tracks were found in the CP/M data
used_tracks = set()
for line in cpm_lines:
    parts = [ int(x, 16) for x in line.split(",") ]
    cpm_track, cpm_sector, identifier = parts

    pet_track = ids_to_pet_tracks[identifier]
    used_tracks.add(pet_track)

# print the unused pet tracks
all_tracks = set(range(1, max(used_tracks)+1))
for unused_track in (all_tracks - used_tracks):
    print unused_track
